"""agrega public_id

Revision ID: 616b67250e7e
Revises: 8fceb832eb5d
Create Date: 2026-04-20 20:27:25.689894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '616b67250e7e'
down_revision: Union[str, Sequence[str], None] = '8fceb832eb5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'public_id')
    # ### end Alembic commands ###
