"""add url_expira_en to pacientes

Revision ID: 6b927c7aef1e
Revises: 616b67250e7e
Create Date: 2026-04-21 14:12:38.747356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b927c7aef1e'
down_revision: Union[str, Sequence[str], None] = '616b67250e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('url_expira_en', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'url_expira_en')
    # ### end Alembic commands ###
